### ISSUE TITLE
[FEAT] 랜딩페이지

### ISSUE THREAD

**Issue by leewoongi** [wisestudy/wisestudy-android#4]
**목적**
- 랜딩페이지 UI 작업

**계획**
- end-date: 5/23
- [x] 랜딩페이지 UI 구성, 폰트 변경
- [x] 앱 시작시 로딩페이지 구현
- [x] 로그인 화면 구현
- [x] 버튼 클릭 후 추가 정보 입력 전환 기능 구현

**특이사항**
- 없음

**Comment by getch37** [comment]
### 작업완료

- due-date: 5/23
- worklog: 5m
